<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="urc_arm">

  <xacro:property name="link1_len" value="0.1" /> <xacro:property name="link2_len" value="0.4" /> <xacro:property name="link3_len" value="0.35" /> <xacro:property name="link4_len" value="0.1" /> <xacro:property name="gripper_len" value="0.15" /> <xacro:property name="PI" value="3.14159265359" />

  <material name="orange"><color rgba="1.0 0.5 0.0 1.0"/></material>
  <material name="grey"><color rgba="0.2 0.2 0.2 1.0"/></material>

  <link name="base_link">
    <visual>
      <geometry><cylinder radius="0.1" length="${link1_len}"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry><cylinder radius="0.1" length="${link1_len}"/></geometry>
    </collision>
  </link>

  <joint name="joint_1" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 ${link1_len/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
  </joint>

  <link name="shoulder_link">
    <visual>
      <geometry><box size="0.1 0.1 0.1"/></geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="joint_2" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="200" velocity="1.0"/>
  </joint>

  <link name="upper_arm_link">
    <visual>
      <origin xyz="0 0 ${link2_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.05" length="${link2_len}"/></geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link2_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.05" length="${link2_len}"/></geometry>
    </collision>
  </link>

  <joint name="joint_3" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="forearm_link"/>
    <origin xyz="0 0 ${link2_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="150" velocity="1.0"/>
  </joint>

  <link name="forearm_link">
    <visual>
      <origin xyz="0 0 ${link3_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${link3_len}"/></geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${link3_len/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="0.04" length="${link3_len}"/></geometry>
    </collision>
  </link>

  <joint name="joint_4" type="revolute">
    <parent link="forearm_link"/>
    <child link="wrist_link"/>
    <origin xyz="0 0 ${link3_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="50" velocity="1.5"/>
  </joint>

  <link name="wrist_link">
    <visual>
      <geometry><box size="0.05 0.08 0.05"/></geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="joint_5" type="revolute">
    <parent link="wrist_link"/>
    <child link="end_effector_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="1 0 0"/> <limit lower="-3.14" upper="3.14" effort="20" velocity="2.0"/>
  </joint>

  <link name="end_effector_link">
    <visual>
      <origin xyz="0 0 ${gripper_len/2}" rpy="0 0 0"/>
      <geometry><box size="0.03 0.1 ${gripper_len}"/></geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${gripper_len/2}" rpy="0 0 0"/>
      <geometry><box size="0.03 0.1 ${gripper_len}"/></geometry>
    </collision>
  </link>
  
  <joint name="camera_joint" type="fixed">
    <parent link="end_effector_link"/>
    <child link="camera_link"/>
    <origin xyz="0.03 0 0.05" rpy="0 -1.57 0"/> </joint>
  <link name="camera_link"/>

  <joint name="tof_joint" type="fixed">
    <parent link="end_effector_link"/>
    <child link="tof_link"/>
    <origin xyz="0.03 0.02 0.05" rpy="0 -1.57 0"/>
  </joint>
  <link name="tof_link"/>

</robot>